version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
    timezone: Europe/Stockholm
  automerged_updates:
    - match:
        dependency_type: 'all'
        update_type: 'semver:minor'
  open-pull-requests-limit: 99
