version: "3.3"
services:
  engine:
    image: qlikcore/engine:12.401.0
    restart: always
    command: -S DocumentDirectory=/docs -S AcceptEULA=${ACCEPT_EULA}
    volumes:
       - ./apps:/docs
    ports:
      - "9076:9076"
